# Generated by Django 2.1.2 on 2018-10-27 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableCategories',
            fields=[
                ('field_id', models.IntegerField(blank=True, db_column='_id', primary_key=True, serialize=False)),
                ('category', models.TextField(blank=True, null=True)),
                ('icon', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'table_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableMovements',
            fields=[
                ('field_id', models.IntegerField(blank=True, db_column='_id', primary_key=True, serialize=False)),
                ('account', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('sign', models.TextField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('transfer', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'table_movements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableAccounts',
            fields=[
                ('field_id', models.IntegerField(blank=True, db_column='_id', primary_key=True, serialize=False)),
                ('account', models.TextField(blank=True, null=True)),
                ('icon', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'table_accounts',
            },
        ),
    ]
