# Generated by Django 2.1.2 on 2018-11-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainspend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='is_subject',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
