# Generated by Django 2.1.2 on 2018-11-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainspend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermethod',
            name='seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
